---
title: "P8105 Final Proposal"
author: "Gwyneth Wei (gw2442); Emma Sexton (els2250); Olivia Wang (hw2852); Mayuri Albal (ma4197) <br>"
date: "2022-11-10"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### **Title**: 

In-depth Analysis of Emma Sexton's Marathon Training for the New York City 2022 Marathon

### **Motivation**: 

Our motivation for this project is to analyze Emma's training habits fro the New York City Marathon to better inform Emma in her future endeavors and to prevent future injuries.

### **Intended Final Products**:

* Generation of Emma's performance throughout the NYC Marathon (November 6th, 2022)

  * Overlay of heartbeat, stride, and running pace throughout each mile of the marathon 
  
* Website demonstrating the statistics and graphing models of Emma's training leading up to the marathon and during the marathon 

### **Anticipated data sources**: 

Data from Strava.com tracked by Garmin watch from March 31st to November 6th

### **The planned analysis/visualizations/coding challenges**:

* Analysis of marathon training reigmen prior to the race

  * Looking at temperature per day
  
  * Elevations at time of run
  
* Marathon statistics per mile throughout the race 

  * Assessing for external factors that could impact/change performance
  
* Graphing overall mileage per month 

* Graphing average mileage per month 

* Visualization of training map 

* Visualization of marathon map and her run 

### **The planned timeline**:

November 12 

* Written proposal submission 

November 15-18

* Projecrt review meeting

* Acquire data by November 18

November 18 - December 10

* Data analysis and production of deliverables

December 10

* Written report submission detailing project description

* Webpage overview of project with explanatory video

* Brief assessment of teammates contributions

December 15

* "In class" discussion of projects

